import * as path from "path";
import { writeFile } from "fs";
import { zConvertHTMLtoPlain, getCommandDocString, getCommandDeclaration } from '../zCommandUtil';
import { zMathFns, zScriptCmds } from '../zscriptCommands';

const indexPath = path.normalize(path.join(__dirname, '..', '..', 'zsc_lang', "index.txt"));


function _setLineMaxCharLength(line: string, maxChar=90, maxCommaLength=10) {
    if (line.length <= maxChar) {
        return line;
    }
    let finalLine = "";
    let newLine = line;
    while (maxChar < newLine.length) {
        let commaPos = newLine.lastIndexOf(',', maxChar);
        let spacePose = newLine.lastIndexOf(' ', maxChar);

        if (commaPos > spacePose) {
            finalLine += newLine.slice(0, commaPos+1);
            newLine = newLine.slice(commaPos, newLine.length);
        } else {
            finalLine += newLine.slice(0, spacePose);
            newLine = newLine.slice(spacePose+1, newLine.length);
        }

        if (newLine.length) {
            finalLine += '\n';
        }
    }
    finalLine += newLine;

    return finalLine;
}

function splitTextLine(text: string, maxChar: number=90, maxCommaLength: number=10){
    let outLine = "";
    let lines = text.split("\n");
    lines.forEach((line, index) => {
        outLine += _setLineMaxCharLength(line);
        if (index < lines.length - 1) {
            outLine += '\n';
        }
    });
    return outLine;
}


function writeIndexFile(){
    let index = `/********************************
* This file is automatically generated.
* DO NOT MODIFY THIS FILE
*
* ZScript Command Definitions
* http://docs.pixologic.com/user-guide/customizing-zbrush/zscripting/command-reference/
*
********************************/\n\n\n`;
    
    for (let obj of [zScriptCmds, zMathFns]){
        for (let cmd in obj){
            let zcommand = obj[cmd];
    
            let docString = zConvertHTMLtoPlain(getCommandDocString(zcommand));
            docString = splitTextLine(docString);
            docString = docString.replace(/\n/g, "\n* ");
            docString = "/**\n* " + docString + "\n*/\n";
    
            index += docString;
            index += splitTextLine(getCommandDeclaration(cmd, zcommand));
            index += "\n\n";
            
        }
    }
    writeFile(indexPath, index, (err) => {
        if (err){
            console.log(err);
        }else{
            console.log("Command file successfully writed here: \"" + indexPath + "\"");
        }        
    });
}

writeIndexFile();